/*
 * JAdultLabel.java
 *
 * Created on June 29, 2007, 9:59 PM
 */

package citibob.swing.typed;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.awt.event.*;
import citibob.exception.*;
import citibob.sql.*;
import java.beans.*;

/**
 *
 * @author  citibob
 */
public class JTypedEditableLabel
extends javax.swing.JPanel
implements TypedWidget, PropertyChangeListener
{

TypedWidget popupWidget;		// The widget we display in the popup to change the value.
String colName;
	
//JFormattedTextField.AbstractFormatter
    /** Creates new form JAdultLabel */
    public JTypedEditableLabel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        popup = new javax.swing.JPopupMenu();
        label = new citibob.swing.typed.JTypedLabel();
        btnChange = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        label.setText("jTypedLabel1");
        add(label, java.awt.BorderLayout.CENTER);

        btnChange.setText("...");
        btnChange.setPreferredSize(new java.awt.Dimension(35, 29));
        btnChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChangeActionPerformed(evt);
            }
        });

        add(btnChange, java.awt.BorderLayout.EAST);

    }// </editor-fold>//GEN-END:initComponents

protected void showPopup()
{
	popup.setPopupSize(getWidth(), 300);
	popup.pack();
	popup.show(this, 0, 0);	
}
	
private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
	showPopup();
}//GEN-LAST:event_btnChangeActionPerformed


/** Lets the user select a value when the button is clicked.  Override this. */
protected Object selectValue()
{ return null; }


public JTypedEditableLabel(JType jt, JFormattedTextField.AbstractFormatter formatter)
{ setJType(jt, formatter); }

// --------------------------------------------------------------
public void setJType(Swinger f)
{ 	label.setJType(f); }

public void setJType(JType jt, JFormattedTextField.AbstractFormatter formatter)
{ label.setJType(jt, formatter); }

public void setPopupWidget(TypedWidget w)
{
	popup.add((Component)w);
	popupWidget = w;
	w.addPropertyChangeListener("value", this);
}

///** Convenience function.
// @param nullText String to use for null value, or else <null> if this is not nullable. */
//public void setJType(citibob.util.KeyedModel kmodel, String nullText)
//{ label.setJType(kmodel, nullText); }


// --------------------------------------------------------------

public boolean isInstance(Object o)
	{ return label.isInstance(o); }
public boolean stopEditing()
	{  return true; }
// --------------------------------------------------------------
/** This can be overridden */
public void setValue(Object o)
	{ label.setValue(o); }

public Object getValue()
	{ return label.getValue(); }
// --------------------------------------------------------------
//** Row (if any) in a RowModel we will bind this to at runtime. */
public String getColName() { return colName; }
/** Row (if any) in a RowModel we will bind this to at runtime. */
public void setColName(String col) { colName = col; }
//public Object clone() throws CloneNotSupportedException { return super.clone(); }
// ---------------------------------------------------


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnChange;
    private citibob.swing.typed.JTypedLabel label;
    private javax.swing.JPopupMenu popup;
    // End of variables declaration//GEN-END:variables

// ============================================================
public void propertyChange(PropertyChangeEvent evt)
{
	popup.setVisible(false);
	Object oldval = getValue();
	Object newval = popupWidget.getValue();
	setValue(newval);
	firePropertyChange("value", oldval, newval);
}
}
