/*
 * BaseJDialogWiz.java
 *
 * Created on January 27, 2007, 9:17 PM
 */

package citibob.swing;

import javax.swing.*;
import citibob.wizard.*;

/**
 * Wraps a content-ful JPanel (that is a Wiz) to create a Wiz.
 * @author  citibob
 */
public class JPanelWizWrapper extends JDialogWiz
{
protected String submit;
JPanelWiz wiz;

/** @params wiz must be a JComponent (JPanel) as well as a Wiz. */
public JPanelWizWrapper(java.awt.Frame owner, JPanelWiz wiz)
{
	super(owner, wiz.getTitle(), true);
	initComponents();
	this.wiz = wiz;
	wiz.setWrapper(this);
	getContentPane().add(wiz, java.awt.BorderLayout.CENTER);
	pack();
}
public JPanelWizWrapper(java.awt.Frame owner, boolean back, boolean next, JPanelWiz wiz)
{
	this(owner, wiz);
	if (!back) bBack.setEnabled(false);
	if (!next) bNext.setEnabled(false);
}
public void getAllValues(java.util.Map map)
{
	map.put("submit", submit);
	wiz.getAllValues(map);
}
	
public void setTitle(String title) { super.setTitle(title); }

public void doSubmit(String submit)
{
	this.submit = submit;
	setVisible(false);
}

/** Should this Wiz screen be cached when "Back" is pressed? */
public boolean getCacheWiz() { return wiz.getCacheWiz(); }

	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        bBack = new javax.swing.JButton();
        bNext = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        bBack.setText("<< Back");
        bBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bBackActionPerformed(evt);
            }
        });

        jPanel1.add(bBack);

        bNext.setText(">> Next");
        bNext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bNextActionPerformed(evt);
            }
        });

        jPanel1.add(bNext);

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bCancelActionPerformed(evt);
            }
        });

        jPanel1.add(bCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void bCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bCancelActionPerformed
	{//GEN-HEADEREND:event_bCancelActionPerformed
		submit = "cancel";
		wiz.cancelPressed();
		setVisible(false);
// TODO add your handling code here:
	}//GEN-LAST:event_bCancelActionPerformed

	private void bNextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bNextActionPerformed
	{//GEN-HEADEREND:event_bNextActionPerformed
		submit = "next";
		wiz.nextPressed();
		setVisible(false);
// TODO add your handling code here:
	}//GEN-LAST:event_bNextActionPerformed

	private void bBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bBackActionPerformed
	{//GEN-HEADEREND:event_bBackActionPerformed
// TODO add your handling code here:
		submit = "back";
		wiz.backPressed();
		setVisible(false);
	}//GEN-LAST:event_bBackActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bNext;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
	
}
